name: Run Tests

on:
  push:
    branches: [ci/cd]
  pull_request:
    branches: [ci/cd]

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DB_TYPE: ${{ secrets.DB_TYPE }}
  HOST_NAME: ${{ secrets.HOST_NAME }}
  DOCKER_DB_HOST_NAME: ${{ secrets.DOCKER_DB_HOST_NAME }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Install and Test Client
      - name: Install and Test Client
        working-directory: ./client
        run: |
          yarn install  # Install dependencies using Yarn
          yarn test     # Run unit tests with Yarn

      # Step 3: Install and Test Server
      - name: Install and Test Server
        working-directory: ./server
        run: |
          yarn install  # Install dependencies using Yarn
          export MONGODB_URI=$MONGODB_URI
          export JWT_SECRET=$JWT_SECRET
          export DB_TYPE=$DB_TYPE
          export HOST_NAME=$HOST_NAME
          export DOCKER_DB_HOST_NAME=$DOCKER_DB_HOST_NAME
          export DB_NAME=$DB_NAME
          yarn test     # Run unit tests with Yarn
